version: 2

models:
  - name: customers
    description: One record per customer, inlcuding identifiers (id, first name, last name), first order, most recent order, number of orders and lifetime value
    columns:
      - name: customer_id
        description: Primary key
        tests:
          - unique
          - not_null
      - name: first_order_date
        description: NULL when a customer has not yet placed an order.
      - name: most_recent_order_date
        description: NULL when a customer has not yet placed an order.
      - name: number_of_orders
        description: Number of orders the customer has placed, 0 when none.
        tests:
          - not_null
      - name: lifetime_amount
        description: Total combined payments received for orders the customer has placed, 0 when none.      
        tests:
          - not_null

  - name: stg_customers
    description: This model cleans up customer data
    columns:
      - name: customer_id
        description: Primary key
        tests:
          - unique
          - not_null

  - name: stg_payment
    description: This staging model cleans up order payment data and filters unsuccessful payments
    columns:
      - name: order_id
        description: Primary key
        tests:
          - unique
          - not_null
      - name: order_amount
        description: Total of successful payments received for this order
        tests:
          - not_null
              
  - name: orders
    description: This model combines order data with payment data
    columns:
      - name: order_id
        description: Primary key
        tests:
          - unique
          - not_null
      - name: customer_id
        description: customer id, unique ID for customer who placed this order
        tests:
          - not_null
      - name: amount
        description: total amount for this order
        tests:
          - not_null
              
  - name: stg_orders
    description: This model cleans up order data
    columns:
      - name: order_id
        description: Primary key
        tests:
          - unique
          - not_null
      - name: customer_id
        description: customer that the order was placed by
        tests:
          - not_null
      - name: order_date
        description: date that the order was placed
        tests:
          - not_null
      - name: status
        description: status of this order
        tests:
          - accepted_values:
              values: ['placed', 'shipped', 'completed', 'return_pending', 'returned']
